### ISSUE TITLE
How do I use this to input a vector of METAR strings, and return the output as a dataframe?

### ISSUE THREAD

**Issue by UNFPAmaldives** [alessandro-gentilini/R-METAR-decoder#1]
If I run the following
`df <- decode_metar(x$OriginalMETARs)`
where `x$OriginalMETARs` is a vector of METAR strings, `decode_metar()` returns a data frame with only a single row decoded.
How do I get your script to decode the entire vector and add each row to the same data frame?

**Comment by alessandro-gentilini** [comment]
@UNFPAmaldives Hello, I made some changes, please try it with your tests.
You can find a code sample at https://github.com/alessandro-gentilini/R-METAR-decoder/blob/master/VRMM_may_2019.R it should produce a plot like this one:
![Rplot](https://user-images.githubusercontent.com/2438459/58379357-753ef300-7fa2-11e9-8351-89d3390dfd7f.png)

**Comment by UNFPAmaldives** [comment]
Awesome — This works. Thank you so much!
